version: "3.2"
services:
  roach:
    image: cockroachdb/cockroach:latest
    volumes:
        - ./data/roach:/cockroach/cockroach-data
    command: start-single-node  --insecure
    ports:
        - "26257:26257"
        - "8080:8080"